# Generated by Django 3.0.8 on 2020-07-20 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=75, verbose_name='Email')),
                ('phone', models.CharField(max_length=13, verbose_name='Номер телефону')),
                ('name', models.CharField(max_length=50, verbose_name="Ім'я")),
                ('course', models.CharField(max_length=100, verbose_name='Курс')),
                ('comment', models.CharField(max_length=250, verbose_name='Коментар')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Додано')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('body', models.TextField(verbose_name='Текст допису')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Час публікації')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('status', models.CharField(choices=[('чорновик', 'Чорновик'), ('опубліковано', 'Опубліковано')], default='draft', max_length=20, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
        ),
    ]
