# Generated by Django 3.0.8 on 2020-07-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200721_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Підзаголовок')),
                ('text', models.CharField(max_length=800, verbose_name='Про себе')),
            ],
            options={
                'verbose_name_plural': 'Про себе',
            },
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Курси'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-publish',), 'verbose_name_plural': 'Пости'},
        ),
    ]
